<?php
        include('../auth/security/securityGeneral.php');
        require ('../../model/bill.php');
        $Bill = new Bill;

        list($data, $product) = $Bill->generateBill($_GET['referencia']);

        require ('./libs/tcpdf_import.php');
        $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
        $pdf->SetCreator('Lotus');
        $pdf->SetAuthor('Lotus');
        $pdf->SetTitle($_GET['referencia']);
        $pdf->SetHeaderData('', '', 'Bill', 'Generated by TCPDF', array(0, 64, 255), array(0, 64, 128));
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        $pdf->SetMargins(10, 10, 10, true);
        $pdf->SetAutoPageBreak(true, 10);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->AddPage();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../css/main.css">
    <title>Bill</title>
</head>
<body>
    <?php
        ob_start();
    ?>
<style>
        .container-bill{
            background: #fff;
            padding: 35px 35px;
            width: 255px;
            border-radius: 5px;
            border: 2px solid #000;
        }
        table{
            border-collapse: collapse;
        }
        table tr th{
            font-family: 'Poppins';
            font-size: 22px;
            padding-bottom: 10px;
        }
        table tr td{
            font-family: 'Nunito';
            
        }
</style>
    <div class="container-bill">
        <?php 
        foreach ($data as $fila) {
        ?>
        <table>
            <tr>
                <th colspan="2">Lotus</th>
            </tr>
            <tr>
                <td colspan="2">Adress: 1234 Lorem Ipsum, Dolor</td>
            </tr>
            <tr>
                <td colspan="2">Tel: 123-456-7890</td>
            </tr>
            <tr style="border-bottom: 1px dashed black;border-top: 1px dashed black; height: 35px;">
                <td style="padding-left: 10px;">Fecha:</td>
                <td><?php echo $fila['date'] ?></td>
            </tr>
            <?php
                
                while($row = $product->fetch_assoc()){
                    ?>
                    <tr>
                        <td><?php echo $row['name_product'] ?></td>
                        <td style="text-align: right;"><?php echo $row['price_u'] ?></td>
                    </tr>
                    <?php
                }
            ?>
            <tr style="border-top: 1px dashed black;">
                <td style="font-family: 'Poppins'; font-size: 20px;">Total</td>
                <td style="text-align: right;"><?php echo $fila['total_prices'] ?></td>
            </tr>
            <tr>
                <td>Sub-total</td>
                <td style="text-align: right;"><?php echo $fila['subtotal'] ?></td>
            </tr>
            <tr>
                <td>IVA</td>
                <td style="text-align: right;"><?php echo ($fila['total_prices'] - $fila['subtotal']) ?></td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;font-weight: bold;font-family: 'Poppins'; font-size: 23px; padding-top: 20px;padding-bottom: 10px;">Gracias</td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;">
                <img alt='Barcode Generator TEC-IT' src='https://barcode.tec-it.com/barcode.ashx?data=<?php echo $fila['num_fact'] ?>&code=Code128&translate-esc=true' style="width: 210px; height: 90px"/>
            </td>
            </tr>
        </table>
        <?php
        }
        ?>
    </div>
    <?php
        $html = ob_get_clean();
        $pdf->writeHTML($html, true, false, true, false, '');
        $pdf->Output('bill.pdf', 'I');
    ?>
</div>
</body>
</html>